# config/cable.yml
development:
  adapter: async
  allowed_request_origins:
    - "http://127.0.0.1:3000"
    - "http://localhost:3000"
    # - "*"
    # - "http://localhost:3000"          # Allow requests from localhost (your Rails dev server)
    # - "http://your-external-app.com"   # Allow requests from any domain or IP as needed
    # - "http://127.0.0.1:3000"  # Replace [YOUR_IP_ADDRESS] with the IP of the machine running Rails
  url: ws://127.0.0.1:3000/cable       # The WebSocket URL for the development server


# development:
#   adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: todo_app_production
